#!/bin/bash

background="$1"
theme="monokai"



if [ $background = "dark" ]; then

    echo "
\"Generated by toggle_dark_light.sh
let g:base16_transparent_background=1
set background=$background
colorscheme $theme
" >> ~/.vimrc.color

    echo "
    Net/ThemeName \"Adwaita-dark\"
    Gtk/ThemeName \"Adwaita-dark\"
    " > ~/.xsettingsd

    kitty +kitten themes --reload-in=all "Monokai Soda"
else
    echo "
\"Generated by toggle_dark_light.sh
let g:base16_transparent_background=0
set background=$background
colorscheme $theme
" >> ~/.vimrc.color

    echo "
    Net/ThemeName \"Radiance\"
    Gtk/ThemeName \"Radiance\"
    " > ~/.xsettingsd

    kitty +kitten themes --reload-in=all "Tomorrow"
fi

killall -HUP xsettingsd
