#!/bin/bash

background="$1"


if [ $background = "dark" ]; then
    sed -i "s/background_opacity .*/background_opacity 0.86/g" ~/.config/kitty/kitty.conf
    kitty +kitten themes --reload-in=all "Monokai"


    echo "
      \"Generated by toggle_dark_light.sh
      let g:base16_transparent_background=1
      set background=dark
      colorscheme monokai
      " > ~/.vimrc.color

    echo "
    Net/ThemeName \"Adwaita-dark\"
    Gtk/ThemeName \"Adwaita-dark\"
    " > ~/.xsettingsd
else
    sed -i "s/background_opacity .*/background_opacity 1.0/g" ~/.config/kitty/kitty.conf
    kitty +kitten themes --reload-in=all "Solarized Light"

    echo "
      \"Generated by toggle_dark_light.sh
      let g:base16_transparent_background=1
      set background=light
      colorscheme solarized
      " > ~/.vimrc.color

    echo "
    Net/ThemeName \"Radiance\"
    Gtk/ThemeName \"Radiance\"
    " > ~/.xsettingsd

fi

killall -USR1 kitty
killall -HUP xsettingsd
