#!/bin/bash

background="$1"
theme="monokai"

echo "
\"Generated by toggle_dark_light.sh
set background=$background
colorscheme $theme
" >> ~/.vimrc.color

if [ $background = "dark" ]; then
    kitty +kitten themes --reload-in=all "Monokai Soda"
else
    kitty +kitten themes --reload-in=all "Atom One Light"
fi

