#!/bin/sh -x

# getting json config values
THEME_CONFIG="$HOME/.config/hypr/themes/$1.json"
WALLPAPER=$(cat $THEME_CONFIG | jq -r ".wallpaper")
GTK_THEME=$(cat $THEME_CONFIG | jq -r ".gtkTheme")
GTK_COLOR_SCHEME=$(cat $THEME_CONFIG | jq -r ".gtkColorScheme")
COLOR_SCHEME=$(cat $THEME_CONFIG | jq -r ".colorScheme")
ICON_THEME=$(cat $THEME_CONFIG | jq -r ".iconTheme")
FONT=$(cat $THEME_CONFIG | jq -r ".font")
KITTY_THEME=$(cat $THEME_CONFIG | jq -r ".kittyTheme")
NVIM_THEME=$(cat $THEME_CONFIG | jq -r ".nvimTheme")
NVIM_BACKGROUND=$(cat $THEME_CONFIG | jq -r ".nvimBackground")
#OBSIDIAN_THEME=$(cat $THEME_CONFIG | jq -r ".obsidianTheme")
VS_CODE_THEME=$(cat $THEME_CONFIG | jq -r ".vsCodeTheme")
VS_CODE_EXTRA_COLORS=$(cat $THEME_CONFIG | jq -r ".vsCodeExtraColors")
DARK_READER_BACKGROUND_COLOR=$(cat $THEME_CONFIG | jq -r ".darkReaderColors.background")
DARK_READER_TEXT_COLOR=$(cat $THEME_CONFIG | jq -r ".darkReaderColors.text")
WOFI_THEME_FILE=$(cat $THEME_CONFIG | jq -r ".wofiThemeFile")
WAYBAR_THEME_FILE=$(cat $THEME_CONFIG | jq -r ".waybarThemeFile")

if [ -f "~/.config/qt5ct/qt5ct.conf" ] ; then
    KVANTUM_THEME=$(cat $THEME_CONFIG | jq -r ".kvantumTheme")
    HAS_KVANTUM=1
else
    HAS_KVANTUM=0
fi

# wallpaper
if [[ -z "${SWAYSOCK}" ]]; then
    # Hyprpaper
    for MON in $(hyprctl monitors -j | jq ".[].name" -r) ; do
        hyprctl hyprpaper wallpaper "$MON,Pictures/wallpapers/$WALLPAPER"
    done
else
    # Sway
    swaymsg "output \"*\" background ~/Pictures/wallpapers/${WALLPAPER} fill"
fi

# Relink wofi theme css
mkdir -p ~/.config/wofi/
ln -fs ~/.config/wofi/$WOFI_THEME_FILE ~/.config/wofi/colors.css

# waybar
killall waybar
ln -fs ~/.config/waybar/$WAYBAR_THEME_FILE ~/.config/waybar/colors.css
waybar &


# gtk theme
gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
gsettings set org.gnome.desktop.interface color-scheme $GTK_COLOR_SCHEME

# Kvantum Theme
if [ $HAS_KVANTUM == 1 ] ; then
    if [[ ! "$KVANTUM_THEME" ]] # If no kvantum theme is set, use gtk2 QT style
    then
        sed -i -E 's/(style=)(.*)/\1'"gtk2"'/g' ~/.config/qt5ct/qt5ct.conf
    else
        sed -i -E 's/(style=)(.*)/\1'"kvantum"'/g' ~/.config/qt5ct/qt5ct.conf
        kvantummanager --set $KVANTUM_THEME
    fi
fi

# font
gsettings set org.gnome.desktop.interface font-name "$FONT"
if [ $HAS_KVANTUM == 1 ] ; then
    sed -i -E 's/(fixed=")(.*)(,.*,.*,.*,.*,.*,.*,.*,.*,.*,.*)/\1'"$FONT"'\3/g' ~/.config/qt5ct/qt5ct.conf
    sed -i -E 's/(general=")(.*)(,.*,.*,.*,.*,.*,.*,.*,.*,.*,.*)/\1'"$FONT"'\3/g' ~/.config/qt5ct/qt5ct.conf
fi

# icon theme
#gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
#if [ $HAS_KVANTUM == 1 ] ; then
#    sed -i -E 's/(icon_theme=)(.*)/\1'"$ICON_THEME"'/g' ~/.config/qt5ct/qt5ct.conf
#fi

# kitty
kitty +kitten themes --reload-in=all "$KITTY_THEME"

# vs code theme
if [ -f ".config/Code - OSS/User/settings.json" ] ; then
    sed -i -E 's/("workbench.colorTheme": ")(.*)(",)/\1'"$VS_CODE_THEME"'\3/g' '.config/Code - OSS/User/settings.json'
    sed -i -E 's/("workbench.colorCustomizations": \{)(.*)(\},)/\1'"$VS_CODE_EXTRA_COLORS"'\3/g' '.config/Code - OSS/User/settings.json'
    sed -i -E 's/("editor.fontFamily": ")(.*)(,.*,.*",)/\1'"$FONT"'\3/g' '.config/Code - OSS/User/settings.json'
fi

# Nvim theme
echo "
\"Generated by $0
set background=$NVIM_BACKGROUND
colorscheme $NVIM_THEME
" > ~/.vimrc.color

# Obsidian theme (change the vault name/directory)
#VAULT_DIRECTORY="Documents/Obsidian Vault"
#sed -i -E 's/("cssTheme": ")(.*)(",)/\1'"$OBSIDIAN_THEME"'\3/g' "$VAULT_DIRECTORY/.obsidian/appearance.json"
#sed -i -E 's/("textFontFamily": ")(.*)(",)/\1'"$FONT"'\3/g' "$VAULT_DIRECTORY/.obsidian/appearance.json"
#sed -i -E 's/("monospaceFontFamily": ")(.*)(",)/\1'"$FONT"'\3/g' "$VAULT_DIRECTORY/.obsidian/appearance.json"
#sed -i -E 's/("interfaceFontFamily": ")(.*)(")/\1'"$FONT"'\3/g' "$VAULT_DIRECTORY/.obsidian/appearance.json"

# Webcord
#rm ~/.config/WebCord/Themes/*
#cp ~/.config/themes/webcord/$COLOR_SCHEME ~/.config/WebCord/Themes/

# Betterdiscord
#cp ~/.config/themes/betterdiscord/$COLOR_SCHEME/themes.json ~/.config/BetterDiscord/data/stable/

# Zathura theme
if [ -f ~/.config/zathura ] ; then
    cp ~/.config/themes/zathura/$COLOR_SCHEME/zathurarc ~/.config/zathura/
fi
